tap "github/gh"
tap "zaquestion/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

# Command line
brew "gnu-tar"
brew "fish"
brew "git"
brew "git-gui"
brew "jq"
brew "md5sha1sum"
brew "nginx"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "wget"
brew "openssl"
brew "htop"
brew "cloc"
brew "hugo"
brew "lastpass-cli"

# Editors
brew "vim"
cask "visual-studio-code"
cask "hex-fiend"
#cask "intellij-idea-ce"

# Languages
brew "go"
cask "java"
brew "gradle"
brew "python3"
brew "node"
brew "yarn"
brew "ruby"

# Fonts
cask "font-inconsolata-g-for-powerline"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-source-code-pro"
cask "font-fira-code"
cask "font-cascadia-mono"

# Apps
cask "db-browser-for-sqlite"
cask "psequel"
cask "iterm2"
cask "superduper"
cask "alfred"
cask "dropbox"
cask "typora"
cask "spectacle"
cask "google-chrome"
cask "menumeters"

# Unproductivity
cask "spotify"
cask "vlc"
cask "aerial"

# Devtools
brew "github/gh/gh"
brew "lab"
brew "ansible"
brew "terraform"
brew "packer"
brew "kubectl"
brew "kops"
brew "helm"
brew "awscli"
cask "session-manager-plugin"
brew "postgres"
brew "terminal-notifier"
cask "slack"
cask "docker"
brew "docker-compose"
brew "docker-credential-helper-ecr"
cask "insomnia"
brew "bbe"

# VMs
#cask "virtualbox"
#cask "virtualbox-extension-pack"
#cask "vagrant"
