#!/bin/bash

DIR=$( cd "$( dirname "$0" )" && pwd )
DOTFILES=$DIR/dotfiles

linked() {
    ln -shf "$DOTFILES/$1" "$HOME/$1"
}

dotfiles() {
    echo Linking all dotfiles to home directory
    linked .vimrc
    linked .vim
    linked .gitconfig
    linked .tmux.conf

    mkdir -p ~/.config/fish/functions
    linked .config/fish/config.fish
    linked .config/fish/functions/fish_prompt.fish

    mkdir -p ~/Library/Application\ Support/Code/User
    linked "Library/Application Support/Code/User/settings.json"
    linked "Library/Application Support/Code/User/keybindings.json"

    mkdir -p ~/.ssh
    linked .ssh/config
}

updateBrew() {
    which brew
    if [ $? -ne 0 ] ; then
        echo Installing Homebrew
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    echo Updating Homebrew
    brew update
    brew upgrade
}

brewBundle() {
    echo Installing packages from Brewfile
    brew bundle --verbose
}

iTermConfig() {
    # Specify the preferences directory
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$DIR/dotfiles/iTerm2"

    # Tell iTerm2 to use the custom preferences in the directory
    defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
}

fish() {
    echo Setting shell to fish
    # Add fish to shells
    grep fish /etc/shells
    if [ $? -ne 0 ]; then
        sudo sh -c "echo /usr/local/bin/fish >> /etc/shells"
    fi

    # Change shell to fish
    chsh -s /usr/local/bin/fish
    mkdir ~/bin
}

codeExtensions() {
    echo Installing VS Code Extensions
    code --install-extension DavidAnson.vscode-markdownlint
    code --install-extension lukehoban.Go
    code --install-extension PeterJausovec.vscode-docker
    code --install-extension donjayamanne.python
    code --install-extension streetsidesoftware.code-spell-checker
    code --install-extension octref.vetur
    code --install-extension mathiasfrohlich.Kotlin
    code --install-extension jebbs.plantuml
}

typr() {
    echo Installing Typr
    if [ ! -d ~/Applications/Typr.app ]; then
        mkdir ~/Applications
        (cd ~/Applications && wget https://github.com/chrisdail/typr/releases/download/v0.1/Typr.zip && unzip Typr.zip && rm Typr.zip)
    fi
}

osxDefaults() {
    echo Mac OS Defaults

    # Key repeat Interval
    defaults write -g InitialKeyRepeat -int 15 # normal minimum is 15 (225 ms)
    defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)

    # Show all files
    defaults write com.apple.finder AppleShowAllFiles YES
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true

    # Unnatural scrolling
    defaults write -g com.apple.swipescrolldirection -bool false

    # Remove all unwanted apps from the dock
    defaults delete com.apple.dock persistent-apps
    defaults delete com.apple.dock persistent-others
    
    killall Dock
    killall Finder /System/Library/CoreServices/Finder.app
}

watchPam() {
    echo Enabling Apple Watch via PAM
    sudo cp misc/pam.d_sudo /etc/pam.d/sudo
}

dotfiles
updateBrew
brewBundle
iTermConfig
fish
codeExtensions
osxDefaults
watchPam
# Note: If you clone my repo, you probably want to comment this out
typr
